name: Windows Release

on:
  push:
      branches: [main]
  pull_request:
      branches: [main]
  release:
      types: [prereleased]

defaults:
  run:
    shell: msys2 {0}

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: setup msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: base-devel git mingw-w64-x86_64-toolchain mingw64/mingw-w64-x86_64-cmake mingw64/mingw-w64-x86_64-ninja mingw64/mingw-w64-x86_64-python mingw64/mingw-w64-x86_64-qt-creator

    - name: checkout source
      uses: actions/checkout@v2

    - name: fetch submodule
      run: |
        cd $GITHUB_WORKSPACE
        git submodule update --init

    - name: version
      run:  |
        cd $GITHUB_WORKSPACE
        version=$(cat "makespec/VERSION").$(cat "makespec/BUILD_VERSION")
        echo "$version"

    - name: build
      run: |
        cd $GITHUB_WORKSPACE
        mkdir release
        cd release
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
        ninja -j $(nproc)
        cpack -G WIX
        cpack -G 7Z

    - name: uploading Windows installer release
      uses: actions/upload-artifact@master
      with:
        name: windows-installer-release
        path: ${{ github.workspace }}/release/*.msi

    - name: uploading Windows 7z release
      uses: actions/upload-artifact@master
      with:
        name: windows-7z-release
        path: ${{ github.workspace }}/release/*.7z
