name: build_windows

on:
  push:
      branches: [main]
  pull_request:
      branches: [main]
  release:
      types: [prereleased]

defaults:
  run:
    shell: msys2 {0}

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: setup msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: base-devel git mingw64/mingw-w64-x86_64-toolchain mingw64/mingw-w64-x86_64-cmake mingw64/mingw-w64-x86_64-ninja mingw64/mingw-w64-x86_64-python mingw64/mingw-w64-x86_64-qt-creator mingw64/mingw-w64-x86_64-qt5-charts

    - name: checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: version
      run:  |
        cd $GITHUB_WORKSPACE
        version=$(cat "makespec/VERSION").$(cat "makespec/BUILD_VERSION")
        echo "$version"
        echo "::set-output name=version::$version"
      id: version

    - name: build
      run: |
        cd $GITHUB_WORKSPACE
        mkdir release
        cd release
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCPACK_GENERATOR=WIX ..
        ninja -j $(nproc)
        cpack
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCPACK_GENERATOR=7Z ..
        ninja -j $(nproc)
        cpack

    - name: uploading Windows installer artifact
      uses: actions/upload-artifact@master
      with:
        name: CoCOM-${{ steps.version.outputs.version }}-win64-installer
        path: ${{ github.workspace }}/release/CoCOM-${{ steps.version.outputs.version }}-win64.msi

    - name: uploading Windows 7z artifact
      uses: actions/upload-artifact@master
      with:
        name: CoCOM-${{ steps.version.outputs.version }}-win64-7z
        path: ${{ github.workspace }}/release/CoCOM-${{ steps.version.outputs.version }}-win64.7z
