name: release_windows

on:
  push:
    tags:
      - '*'

defaults:
  run:
    shell: msys2 {0}

jobs:

  release:
    runs-on: windows-latest

    steps:
    - name: setup msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: base-devel git mingw-w64-x86_64-toolchain mingw64/mingw-w64-x86_64-cmake mingw64/mingw-w64-x86_64-ninja mingw64/mingw-w64-x86_64-python mingw64/mingw-w64-x86_64-qt-creator

    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: fetch submodule
      run: |
        cd $GITHUB_WORKSPACE
        git submodule update --init --depth 1

    - name: version
      run:  |
        cd $GITHUB_WORKSPACE
        version=$(cat "makespec/VERSION").$(cat "makespec/BUILD_VERSION")
        echo "$version"
        echo "::set-output name=version::$version"
      id: version

    - name: build
      run: |
        cd $GITHUB_WORKSPACE
        mkdir release
        cd release
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
        ninja -j $(nproc)
        cpack -G WIX
        cpack -G 7Z

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: true
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        # body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload Windows installer release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/release/CoCOM-${{ steps.version.outputs.version }}-win64.msi
        asset_name: CoCOM-${{ steps.version.outputs.version }}-win64.msi
        asset_content_type: application/octet-stream

    - name: upload Windows 7z release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/release/CoCOM-${{ steps.version.outputs.version }}-win64.7z
        asset_name: CoCOM-${{ steps.version.outputs.version }}-win64.7z
        asset_content_type: application/x-gtar
